%% PPO Agent (your existing implementation)
function agent = createPPOAgent(obsInfo, actInfo)
% Input path
inPath = [
    sequenceInputLayer(prod(obsInfo.Dimension), Name="obsInLyr")
    lstmLayer(128, Name="lstmLayer")
    ];

% Mean path
meanPath = [
    reluLayer(Name="reluLayerMean");
    fullyConnectedLayer(prod(actInfo.Dimension),Name="fullyConnectedLayer1")
    sigmoidLayer(Name="meanOutLyrSigmoidLayer")
    ];

% Standard deviation path
sdevPath = [
    reluLayer(Name="reluLayerStdv")
    fullyConnectedLayer(prod(actInfo.Dimension), Name="fullyConnectedLayer2")
    softplusLayer(Name="stdOutLyrSoftplusLayer")
    ];

actorNet = dlnetwork;
actorNet = addLayers(actorNet, inPath);
actorNet = addLayers(actorNet, meanPath);
actorNet = addLayers(actorNet, sdevPath);
actorNet = connectLayers(actorNet, "lstmLayer", "reluLayerMean/in");
actorNet = connectLayers(actorNet, "lstmLayer", "reluLayerStdv/in");
actorNet = initialize(actorNet);

actor = rlContinuousGaussianActor(actorNet, obsInfo, actInfo, ...
    ActionMeanOutputNames="meanOutLyrSigmoidLayer",...
    ActionStandardDeviationOutputNames="stdOutLyrSoftplusLayer",...
    ObservationInputNames="obsInLyr");

% Critic network
criticNet = [
    sequenceInputLayer(prod(obsInfo.Dimension))
    lstmLayer(128)
    reluLayer
    fullyConnectedLayer(1)
    ];

criticNet = dlnetwork(criticNet);
critic = rlValueFunction(criticNet, obsInfo);
agent = rlPPOAgent(actor, critic);

% outputDir = '/Users/mohammadfarid/Desktop/results geochemistry/actor critic nets';  % Change this path% Create directory if it doesn't exist
% if ~isfolder(outputDir)
%     mkdir(outputDir);
% end
% agent_name = 'PPO';
% fig_name = sprintf('%s-Actor Net', agent_name);
% [G, h, fig] = plotNetworkAsGraph(actorNet, ...
%     'SavePath', outputDir, ...
%     'SaveName', fig_name, ...
%     'SaveFormats', {'fig', 'jpeg', 'tif'}, ...
%     'Resolution', 1200, ...
%     'NodeFontSize', 14, ...
%     'MarkerSize', 10, ...
%     'NodeColor', [0.2, 0.6, 0.8], ...
%     'LineWidth', 2, ...
%     'Layout', 'layered', ...
%     'title',fig_name,...
%     'ShowLabels', true, ...
%     'BackgroundColor', [0.95, 0.95, 0.95], ...
%     'GridOn', true);
% fig_name = sprintf('%s-Critic Net', agent_name);
% [G, h, fig] = plotNetworkAsGraph(criticNet, ...
%     'SavePath', outputDir, ...
%     'SaveName', fig_name, ...
%     'SaveFormats', {'fig', 'jpeg', 'tif'}, ...
%     'Resolution', 1200, ...
%     'NodeFontSize', 14, ...
%     'MarkerSize', 10, ...
%     'NodeColor', [0.2, 0.6, 0.8], ...
%     'LineWidth', 2, ...
%     'Layout', 'layered', ...
%     'title',fig_name,...
%     'ShowLabels', true, ...
%     'BackgroundColor', [0.95, 0.95, 0.95], ...
%     'GridOn', true);

end
