function agent = createTD3Agent(obsInfo, actInfo)
% RNN-based actor
actorNet = [
    sequenceInputLayer(prod(obsInfo.Dimension), Name="obsIn")
    lstmLayer(128, OutputMode="sequence", Name="actorLSTM")
    fullyConnectedLayer(prod(actInfo.Dimension), Name="actorFC")
    sigmoidLayer(Name="actorSigmoid")
    ];
actorNet = dlnetwork(layerGraph(actorNet));
actorNet = initialize(actorNet);
actor = rlContinuousDeterministicActor(actorNet, obsInfo, actInfo);

% Build one critic with matching RNN structure
    function criticNet = buildCritic()
        obsPath = [
            sequenceInputLayer(prod(obsInfo.Dimension), Name="obsInCrit")
            lstmLayer(128, OutputMode="sequence", Name="obsLSTM")
            reluLayer(Name="obsRelu")
            ];
        actPath = [
            sequenceInputLayer(prod(actInfo.Dimension), Name="actInCrit")
            lstmLayer(128, OutputMode="sequence", Name="actLSTM")
            reluLayer(Name="actRelu")
            ];
        commonPath = [
            additionLayer(2, Name="add")
            reluLayer(Name="commonRelu")
            fullyConnectedLayer(128, Name="commonFC")
            reluLayer(Name="commonRelu2")
            fullyConnectedLayer(1, Name="qValue")
            ];
        lgraph = layerGraph();
        lgraph = addLayers(lgraph, obsPath);
        lgraph = addLayers(lgraph, actPath);
        lgraph = addLayers(lgraph, commonPath);
        lgraph = connectLayers(lgraph, 'obsRelu', 'add/in1');
        lgraph = connectLayers(lgraph, 'actRelu', 'add/in2');
        criticNet = dlnetwork(lgraph);
        criticNet = initialize(criticNet);
    end

% Create twin critics
criticNet1 = buildCritic();
criticNet2 = buildCritic();

critic1 = rlQValueFunction(criticNet1, obsInfo, actInfo, ...
    ObservationInputNames="obsInCrit", ActionInputNames="actInCrit");
critic2 = rlQValueFunction(criticNet2, obsInfo, actInfo, ...
    ObservationInputNames="obsInCrit", ActionInputNames="actInCrit");

agent = rlTD3Agent(actor, [critic1 critic2]);

outputDir = '/Users/mohammadfarid/Desktop/results geochemistry/actor critic nets';  % Change this path% Create directory if it doesn't exist
agent_name = 'TD3';
fig_name = sprintf('%s-Actor Net', agent_name);
[G, h, fig] = plotNetworkAsGraph(actorNet, ...
    'SavePath', outputDir, ...
    'SaveName', fig_name, ...
    'SaveFormats', {'fig', 'jpeg', 'tif'}, ...
    'Resolution', 1200, ...
    'NodeFontSize', 14, ...
    'MarkerSize', 10, ...
    'NodeColor', [0.2, 0.6, 0.8], ...
    'LineWidth', 2, ...
    'Layout', 'layered', ...
    'title',fig_name,...
    'ShowLabels', true, ...
    'BackgroundColor', [0.95, 0.95, 0.95], ...
    'GridOn', true);
fig_name = sprintf('%s-Critic Net', agent_name);
[G, h, fig] = plotNetworkAsGraph(criticNet1, ...
    'SavePath', outputDir, ...
    'SaveName', fig_name, ...
    'SaveFormats', {'fig', 'jpeg', 'tif'}, ...
    'Resolution', 1200, ...
    'NodeFontSize', 14, ...
    'MarkerSize', 10, ...
    'NodeColor', [0.2, 0.6, 0.8], ...
    'LineWidth', 2, ...
    'Layout', 'layered', ...
    'title',fig_name,...
    'ShowLabels', true, ...
    'BackgroundColor', [0.95, 0.95, 0.95], ...
    'GridOn', true);

end
