function agent = createTRPOAgent(obsInfo, actInfo)
% TRPO Agent with feedforward networks (no LSTM)

% Feedforward input path
inPath = [
    featureInputLayer(prod(obsInfo.Dimension), Name="obsInLyr")
    fullyConnectedLayer(128, Name="commonFC")
    reluLayer(Name="commonRelu")
    ];

% Mean path
meanPath = [
    fullyConnectedLayer(128, Name="meanFC")
    reluLayer(Name="reluLayerMean");
    fullyConnectedLayer(prod(actInfo.Dimension))
    sigmoidLayer(Name="meanOutLyr")
    ];

% Std path
sdevPath = [
    fullyConnectedLayer(128, Name="stdFC")
    reluLayer(Name="reluLayerStdv")
    fullyConnectedLayer(prod(actInfo.Dimension))
    softplusLayer(Name="stdOutLyr")
    ];

% Build network
actorNet = dlnetwork;
actorNet = addLayers(actorNet, inPath);
actorNet = addLayers(actorNet, meanPath);
actorNet = addLayers(actorNet, sdevPath);
actorNet = connectLayers(actorNet, "commonRelu", "meanFC");
actorNet = connectLayers(actorNet, "commonRelu", "stdFC");
actorNet = initialize(actorNet);

actor = rlContinuousGaussianActor(actorNet, obsInfo, actInfo, ...
    ActionMeanOutputNames="meanOutLyr",...
    ActionStandardDeviationOutputNames="stdOutLyr",...
    ObservationInputNames="obsInLyr");

% Feedforward critic
criticNet = [
    featureInputLayer(prod(obsInfo.Dimension))
    fullyConnectedLayer(128)
    reluLayer
    fullyConnectedLayer(64)
    reluLayer
    fullyConnectedLayer(1)
    ];

criticNet = dlnetwork(criticNet);
critic = rlValueFunction(criticNet, obsInfo);
agent = rlTRPOAgent(actor, critic);

outputDir = '/Users/mohammadfarid/Desktop/results geochemistry/actor critic nets';  % Change this path% Create directory if it doesn't exist
if ~isfolder(outputDir)
    mkdir(outputDir);
end
agent_name = 'TRPO';
fig_name = sprintf('%s-Actor Net', agent_name);
[G, h, fig] = plotNetworkAsGraph(actorNet, ...
    'SavePath', outputDir, ...
    'SaveName', fig_name, ...
    'SaveFormats', {'fig', 'jpeg', 'tif'}, ...
    'Resolution', 1200, ...
    'NodeFontSize', 14, ...
    'MarkerSize', 10, ...
    'NodeColor', [0.2, 0.6, 0.8], ...
    'LineWidth', 2, ...
    'Layout', 'layered', ...
    'title',fig_name,...
    'ShowLabels', true, ...
    'BackgroundColor', [0.95, 0.95, 0.95], ...
    'GridOn', true);
fig_name = sprintf('%s-Critic Net', agent_name);
[G, h, fig] = plotNetworkAsGraph(criticNet, ...
    'SavePath', outputDir, ...
    'SaveName', fig_name, ...
    'SaveFormats', {'fig', 'jpeg', 'tif'}, ...
    'Resolution', 1200, ...
    'NodeFontSize', 14, ...
    'MarkerSize', 10, ...
    'NodeColor', [0.2, 0.6, 0.8], ...
    'LineWidth', 2, ...
    'Layout', 'layered', ...
    'title',fig_name,...
    'ShowLabels', true, ...
    'BackgroundColor', [0.95, 0.95, 0.95], ...
    'GridOn', true);

end
