function agent = createA3CAgent(obsInfo, actInfo)
% A3C (Asynchronous Advantage Actor-Critic) Agent

% Same actor architecture as A2C
inPath = [
    sequenceInputLayer(prod(obsInfo.Dimension), Name="obsInLyr")
    lstmLayer(128, Name="actorLSTM", OutputMode="sequence")
    ];

meanPath = [
    reluLayer(Name="reluLayerMean");
    fullyConnectedLayer(prod(actInfo.Dimension))
    sigmoidLayer(Name="meanOutLyr")
    ];

sdevPath = [
    reluLayer(Name="reluLayerStdv")
    fullyConnectedLayer(prod(actInfo.Dimension))
    softplusLayer(Name="stdOutLyr")
    ];

actorNet = dlnetwork;
actorNet = addLayers(actorNet, inPath);
actorNet = addLayers(actorNet, meanPath);
actorNet = addLayers(actorNet, sdevPath);
actorNet = connectLayers(actorNet, "actorLSTM", "reluLayerMean/in");
actorNet = connectLayers(actorNet, "actorLSTM", "reluLayerStdv/in");
actorNet = initialize(actorNet);

actor = rlContinuousGaussianActor(actorNet, obsInfo, actInfo, ...
    ActionMeanOutputNames="meanOutLyr",...
    ActionStandardDeviationOutputNames="stdOutLyr",...
    ObservationInputNames="obsInLyr");

% Same critic as A2C
criticNet = [
    sequenceInputLayer(prod(obsInfo.Dimension))
    lstmLayer(128, OutputMode="sequence")
    reluLayer
    fullyConnectedLayer(64)
    reluLayer
    fullyConnectedLayer(1)
    ];

criticNet = dlnetwork(criticNet);
critic = rlValueFunction(criticNet, obsInfo);

agent = rlACAgent(actor, critic);

outputDir = '/Users/mohammadfarid/Desktop/results geochemistry/actor critic nets';  % Change this path% Create directory if it doesn't exist
if ~isfolder(outputDir)
    mkdir(outputDir);
end
agent_name = 'A3C';
fig_name = sprintf('%s-Actor Net', agent_name);
[G, h, fig] = plotNetworkAsGraph(actorNet, ...
    'SavePath', outputDir, ...
    'SaveName', fig_name, ...
    'SaveFormats', {'fig', 'jpeg', 'tif'}, ...
    'Resolution', 1200, ...
    'NodeFontSize', 14, ...
    'MarkerSize', 10, ...
    'NodeColor', [0.2, 0.6, 0.8], ...
    'LineWidth', 2, ...
    'Layout', 'layered', ...
    'title',fig_name,...
    'ShowLabels', true, ...
    'BackgroundColor', [0.95, 0.95, 0.95], ...
    'GridOn', true);
fig_name = sprintf('%s-Critic Net', agent_name);
[G, h, fig] = plotNetworkAsGraph(criticNet, ...
    'SavePath', outputDir, ...
    'SaveName', fig_name, ...
    'SaveFormats', {'fig', 'jpeg', 'tif'}, ...
    'Resolution', 1200, ...
    'NodeFontSize', 14, ...
    'MarkerSize', 10, ...
    'NodeColor', [0.2, 0.6, 0.8], ...
    'LineWidth', 2, ...
    'Layout', 'layered', ...
    'title',fig_name,...
    'ShowLabels', true, ...
    'BackgroundColor', [0.95, 0.95, 0.95], ...
    'GridOn', true);

end
