function results = trainWithEvolutionaryStrategy(agent, env, agent_name,base_path)
    % Evolutionary Strategy training options with valid names
    mkdir([base_path,'/','agents',agent_name])
    esOpts = rlEvolutionStrategyTrainingOptions(...
        PopulationSize=20, ...              % Number of individuals
        MaxGenerations=500, ...              % Number of generations
        MaxStepsPerEpisode=128, ...
        StopTrainingCriteria="none", ...   % Disable auto-stop
        StopTrainingValue=0, ...
        SimulationStorageType= "file", ...
        SaveAgentCriteria="EpisodeReward",...
        SaveAgentDirectory=[base_path,'/','agents',agent_name],...        
        UseParallel=1, ...
        Verbose=0);
    
    % Train
    training_stats = trainWithEvolutionStrategy(agent, env, esOpts);
    
    % Collect results
    results = collectTrainingResults(env, agent, agent_name);
    results.training_stats = training_stats;
end
